//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/PRECIP001.pso /Fcshaderdump19/PRECIP001.pso.dis
//
//
// Parameters:
//
float3 AmbientColor : register(c0);
sampler2D ScreenSpace : register(s0);
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   AmbientColor const_0       1
//   ScreenSpace         texture_0       1
//


// Structures:

struct VS_OUTPUT {
    float4 color_0 : COLOR0;
    float2 ScreenOffset : TEXCOORD0;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float4 r0;

    r0.xyzw = tex2D(ScreenSpace, IN.ScreenOffset.xy);
    OUT.color_0.a = r0.w * IN.color_0.a;
    OUT.color_0.rgb = saturate((IN.color_0.rgb * r0.xyz) + AmbientColor.rgb);

    return OUT;
};

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
