//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/WATERHMAP006.pso /Fcshaderdump19/WATERHMAP006.pso.dis
//
//
// Parameters:
//
sampler2D HeightMap : register(s0);
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   HeightMap    texture_0       1
//


// Structures:

struct VS_OUTPUT {
    float2 HeightUV : TEXCOORD0;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float4 r0;

    r0.xyzw = tex2D(HeightMap, IN.HeightUV.xy);
    OUT.color_0.a = 1;
    OUT.color_0.rgb = abs(r0.x);

    return OUT;
};

// approximately 4 instruction slots used (1 texture, 3 arithmetic)
