//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/WATERHMAP005.pso /Fcshaderdump19/WATERHMAP005.pso.dis
//
//
// Parameters:
//
int fResolution : register(c2);
float4 TESR_Tick : register(c3);
float4 TESR_WaveParams : register(c4);

sampler2D amplitudeSamp : register(s0);
sampler3D TESR_samplerWater : register(s3) < string ResourceName = "Water\water_NRM.dds"; > = sampler_state { ADDRESSU = WRAP; ADDRESSV = WRAP; ADDRESSW = WRAP; MAGFILTER = LINEAR; MINFILTER = LINEAR; MIPFILTER = LINEAR; };

//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   fResolution   const_2       1
//   amplitudeSamp texture_0       1
//


// Structures:

struct VS_OUTPUT {
    float2 texcoord_0 : TEXCOORD0;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float frame = TESR_Tick.y * TESR_WaveParams.z / 1500;
    OUT.color_0 = tex3D(TESR_samplerWater, float3(IN.texcoord_0.xy, frac(frame)));
    return OUT;
};