//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/WATERHMAP002.pso /Fcshaderdump19/WATERHMAP002.pso.dis
//
//
// Parameters:
//
float fPassNum : register(c1);
sampler2D sampButterfly : register(s0);
sampler2D sampSourceImage : register(s2);
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   fPassNum        const_1       1
//   sampButterfly   texture_0       1
//   sampSourceImage texture_2       1
//


// Structures:

struct VS_OUTPUT {
    float2 texcoord_0 : TEXCOORD0;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float4 r0;
    float4 r1;
    float4 r2;
    float2 r3;

    r0.y = fPassNum.x;
    r0.x = IN.texcoord_0.y;
    r1.xyzw = tex2D(sampButterfly, r0.xy);
    r0.y = r1.y;
    r2.y = abs(r1.x);
    r0.x = IN.texcoord_0.x;
    r0.xyzw = tex2D(sampSourceImage, r0.xy);
    r2.x = IN.texcoord_0.x;
    r2.xyzw = tex2D(sampSourceImage, r2.xy);
    r3.x = (r1.z * r2.x) - (r1.w * r2.w);
    r3.y = (r1.w * r2.x) + (r1.z * r2.w);
    r1.xy = (r1.x >= 0.0 ? r3.xy : -r3.xy);
    OUT.color_0.a = r0.w + r1.y;
    OUT.color_0.rgb = r0.x + r1.x;

    return OUT;
};

// approximately 19 instruction slots used (3 texture, 16 arithmetic)
