//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SKYCLOUDS.vso /Fcshaderdump19/SKYCLOUDS.vso.dis
//
//
// Parameters:
//
float4 BlendColor[3] : register(c4);
row_major float4x4 ModelViewProj : register(c0);
float TexCoordYOff : register(c12);
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   ModelViewProj[0] const_0        1
//   ModelViewProj[1] const_1        1
//   ModelViewProj[2] const_2        1
//   ModelViewProj[3] const_3        1
//   BlendColor[0]    const_4        1
//   BlendColor[1]    const_5        1
//   BlendColor[2]    const_6        1
//   TexCoordYOff  const_12      1
//


// Structures:

struct VS_INPUT {
    float4 position : POSITION;
    float4 texcoord_0 : TEXCOORD0;
    float4 color_0 : COLOR0;
};

struct VS_OUTPUT {
    float4 position : POSITION;
    float2 texcoord_0 : TEXCOORD0;
    float2 texcoord_1 : TEXCOORD1;
    float2 texcoord_2 : TEXCOORD2;
    float2 texcoord_3 : TEXCOORD3;
    float4 color_0 : COLOR0;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

    float3 r0;

    r0.xyz = (IN.color_0.r * BlendColor[0].rgb) + (BlendColor[1].rgb * IN.color_0.g);
    OUT.color_0.a = BlendColor[0].a * IN.color_0.a;
    OUT.color_0.rgb = (IN.color_0.b * BlendColor[2].rgb) + r0.xyz;
    r0.xy = mul(float2x4(ModelViewProj[0].xyzw, ModelViewProj[1].xyzw), IN.position.xyzw);
    r0.z = dot(ModelViewProj[3].xyzw, IN.position.xyzw);
    OUT.position.xyzw = r0.xyzz;
    r0.y = TexCoordYOff.x + IN.texcoord_0.y;
    r0.x = IN.texcoord_0.x;
    OUT.texcoord_0.xy = r0.xy;
    OUT.texcoord_1.xy = r0.xy;
    OUT.texcoord_2.xy = r0.xy;
    OUT.texcoord_3.xy = r0.xy;

    return OUT;
};

// approximately 14 instruction slots used
