//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SKYT.vso /Fcshaderdump19/SKYT.vso.dis
//
//
// Parameters:
//
float4 BlendColor[3] : register(c4);
row_major float4x4 ModelViewProj : register(c0);
row_major float4x4 TESR_InvViewProjectionTransform : register(c97);
float4 TESR_FogColor : register(c24);
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   ModelViewProj[0] const_0        1
//   ModelViewProj[1] const_1        1
//   ModelViewProj[2] const_2        1
//   ModelViewProj[3] const_3        1
//   BlendColor[0]    const_4        1
//   BlendColor[1]    const_5        1
//   BlendColor[2]    const_6        1
//


// Structures:

struct VS_INPUT {
    float4 position : POSITION;
    float4 texcoord_0 : TEXCOORD0;
    float4 color_0 : COLOR0;
};

struct VS_OUTPUT {
    float4 position : POSITION;
    float2 texcoord_0 : TEXCOORD0;
    float2 texcoord_1 : TEXCOORD1;
    float2 texcoord_2 : TEXCOORD2;
    float2 texcoord_3 : TEXCOORD3;
    float4 color_0 : COLOR0;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

    float3 r0;
    float4 r1;
    float fogStart = 200.0f;

    r0.xyz = (IN.color_0.r * BlendColor[0].rgb) + (BlendColor[1].rgb * IN.color_0.g);
    OUT.color_0.a = BlendColor[0].a * IN.color_0.a;
    r1 = mul(ModelViewProj, IN.position.xyzw);
    float4 pos = mul(r1, TESR_InvViewProjectionTransform);

    OUT.color_0.rgb = max(TESR_FogColor.rgb * saturate(fogStart / abs(pos.z)), (IN.color_0.b * BlendColor[2].rgb) + r0.xyz);

    r0.xy = mul(float2x4(ModelViewProj[0].xyzw, ModelViewProj[1].xyzw), IN.position.xyzw);
    r0.z = dot(ModelViewProj[3].xyzw, IN.position.xyzw);
    OUT.position.xyzw = r0.xyzz;

    OUT.texcoord_0.xy = IN.texcoord_0.xy;
    OUT.texcoord_1.xy = IN.texcoord_0.xy;
    OUT.texcoord_2.xy = IN.texcoord_0.xy;
    OUT.texcoord_3.xy = IN.texcoord_0.xy;

    return OUT;
};

// approximately 12 instruction slots used
