//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SLS2034.pso /Fcshaderdump19/SLS2034.pso.dis
//
//
// Parameters:
//
float4 AmbientColor : register(c1);
sampler2D AttenuationMap : register(s4);
sampler2D BaseMap : register(s0);
float4 EmittanceColor : register(c6);
sampler2D GlowMap : register(s3);
sampler2D NormalMap : register(s1);
float4 PSLightColor[4] : register(c2);
sampler2D ShadowMap : register(s5);
sampler2D ShadowMaskMap : register(s6);
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   AmbientColor   const_1       1
//   PSLightColor[0]   const_2        1
//   PSLightColor[1]   const_3        1
//   PSLightColor[2]   const_4        1
//   EmittanceColor const_6       1
//   BaseMap        texture_0       1
//   NormalMap      texture_1       1
//   GlowMap        texture_3       1
//   AttenuationMap texture_4       1
//   ShadowMap      texture_5       1
//   ShadowMaskMap  texture_6       1
//


// Structures:

struct VS_OUTPUT {
    float2 BaseUV : TEXCOORD0;
    float3 texcoord_1 : TEXCOORD1_centroid;
    float3 texcoord_2 : TEXCOORD2_centroid;
    float3 texcoord_3 : TEXCOORD3_centroid;
    float4 texcoord_4 : TEXCOORD4;
    float4 texcoord_5 : TEXCOORD5;
    float4 texcoord_6 : TEXCOORD6;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	expand(v)		(((v) - 0.5) / 0.5)
#define	compress(v)		(((v) * 0.5) + 0.5)
#define	shade(n, l)		max(dot(n, l), 0)
#define	shades(n, l)		saturate(dot(n, l))

    float1 att0;
    float1 att1;
    float1 att11;
    float1 att6;
    float3 q12;
    float3 q14;
    float3 q3;
    float4 r0;
    float4 r1;
    float3 r2;
    float4 r6;
    float3 t2;
    float1 t5;

    t5.x = tex2D(ShadowMaskMap, IN.texcoord_6.zw);			// partial precision
    t2.xyz = tex2D(ShadowMap, IN.texcoord_6.xy);			// partial precision
    r6.xyzw = tex2D(NormalMap, IN.BaseUV.xy);			// partial precision
    r1.xyzw = tex2D(GlowMap, IN.BaseUV.xy);
    r0.xyzw = tex2D(BaseMap, IN.BaseUV.xy);			// partial precision
    att6.x = tex2D(AttenuationMap, IN.texcoord_5.zw);			// partial precision
    att0.x = tex2D(AttenuationMap, IN.texcoord_5.xy);			// partial precision
    att1.x = tex2D(AttenuationMap, IN.texcoord_4.xy);			// partial precision
    att11.x = tex2D(AttenuationMap, IN.texcoord_4.zw);			// partial precision
    q3.xyz = normalize(expand(r6.xyz));			// partial precision
    r0.xyz = shades(q3.xyz, normalize(IN.texcoord_3.xyz)) * PSLightColor[2].rgb;			// partial precision
    q12.xyz = saturate((1 - att1.x) - att11.x) * (shades(q3.xyz, normalize(IN.texcoord_2.xyz)) * PSLightColor[1].rgb);			// partial precision
    q14.xyz = (((t5.x * (t2.xyz - 1)) + 1) * (shades(q3.xyz, IN.texcoord_1.xyz) * PSLightColor[0].rgb)) + q12.xyz;			// partial precision
    r2.xyz = (saturate((1 - att0.x) - att6.x) * r0.xyz) + q14.xyz;			// partial precision
    OUT.color_0.a = r0.w;			// partial precision
    OUT.color_0.rgb = r2.xyz + ((r1.xyz * EmittanceColor.rgb) + AmbientColor.rgb);			// partial precision

    return OUT;
};

// approximately 45 instruction slots used (9 texture, 36 arithmetic)
