//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/GRASS2030.vso /Fcshaderdump19/GRASS2030.vso.dis
//
//
// Parameters:
//
float3 DiffuseDir : register(c0);
float3 DiffuseColor : register(c1);
float3 ScaleMask : register(c2);
float4 WindData : register(c4);
float4 AlphaParam : register(c5);
float4 AmbientColor : register(c6);
float4 AddlParams : register(c7);
float4 ShadowProjData : register(c8);
row_major float4x4 ModelViewProj : register(c9);
float4 ShadowProjTransform : register(c13);
float4 FogColor : register(c14);
float4 FogParam : register(c15);
float4 InstanceData[228] : register(c20);
float4 TESR_GrassScale : register(c248);
row_major float4x4 TESR_ShadowCameraToLightTransformNear : register(c249);
row_major float4x4 TESR_ShadowCameraToLightTransformFar : register(c16);

//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   DiffuseDir          const_0       1
//   DiffuseColor        const_1       1
//   ScaleMask           const_2       1
//   WindData            const_4       1
//   AlphaParam          const_5       1
//   AmbientColor        const_6       1
//   AddlParams          const_7       1
//   ShadowProjData      const_8       1
//   ModelViewProj[0]       const_9        1
//   ModelViewProj[1]       const_10        1
//   ModelViewProj[2]       const_11        1
//   ModelViewProj[3]       const_12        1
//   ShadowProjTransform const_13      1
//   FogColor            const_14      1
//   FogParam            const_15      1
//   InstanceData[0]        const_20       1
//   InstanceData[1]        const_21       1
//


// Structures:

struct VS_INPUT {
    float4 position : POSITION;
    float4 color_0 : COLOR0;
    float4 texcoord_0 : TEXCOORD0;
    float4 texcoord_1 : TEXCOORD1;
};

struct VS_OUTPUT {
    float4 color_0 : COLOR0;
    float4 position : POSITION;
    float2 texcoord_0 : TEXCOORD0;
    float3 texcoord_4 : TEXCOORD4;
	float4 texcoord_5 : TEXCOORD5;
    float4 texcoord_6 : TEXCOORD6;
    float4 texcoord_7 : TEXCOORD7;
    float4 texcoord_8 : TEXCOORD8;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

#define	PI				3.14159274
#define	anglei(v)		(((v) + PI) / (2 * PI))
#define	angler(v)		(((v) * (2 * PI)) - PI)
#define	fracr(v)		angler(frac(anglei(v)))	// signed modulo % PI
#define	expand(v)		(((v) - 0.5) / 0.5)
#define	shades(n, l)	saturate(dot(n, l))
#define	sqr(v)			((v) * (v))

    const int4 const_16 = {0, 2, -1, 1};
	
    float4 q0;
    float4 r0;
    float4 r1;
    float4 r2;
    float2 r3;
    float3 r4;
	float3 scale;
	
    r1.xyzw = frac(InstanceData[0 + IN.texcoord_1.x]);
    r1.xyz = r1.xyz - 0.5;
    q0.x = InstanceData[0 + IN.texcoord_1.x].y + InstanceData[0 + IN.texcoord_1.x].x;
    OUT.color_0.rgb = FogColor.rgb;
    OUT.texcoord_0.xy = IN.texcoord_0.xy;
    r0.xyz = 2 * r1.xyz;
    r2.xyz = abs(r0.xyz);
    r0.w = -r0.y;
    r2.xyzw = (r2.yzxz >= r2.xxyy ? 1.0 : 0.0);
    r3.xy = r2.yw * r2.xz;
    r1.x = (2 * r1.y) - r0.z;
    r1.yz = r0.x * const_16.zw;
    r2.z = r3.y * r1.z;
    r2.xy = (r3.y * r1.xy) + r0.wx;
    r1.x = -r2.x;
    r1.yz = (r0.zy * const_16.zw) - r2.yz;
    r1.xyz = (r3.x * r1.xyz) + r2.xyz;
    r4.xyz = normalize(r1.xyz);
    r2.x = expand(frac(q0.x / 17));
    r2.w = sqrt(1.0 - sqr(r2.x));
    r2.z = 0;
    r2.y = -r2.w;
	scale.xyz = ScaleMask.xyz * TESR_GrassScale.xyz;
    r1.xyz = (((0.01 * InstanceData[0 + IN.texcoord_1.x].w) * scale.xyz) + TESR_GrassScale.w) * IN.position.xyz;
    r1.xyz = (r1.z * r0.xyz) + ((dot(r2.xyz, r1.xyz) * cross(r4.xyz, r0.xyz)) + (r4.xyz * dot(r2.wxz, r1.xyz)));
    r2.xyz = ((r1.w * IN.color_0.rgb) * shades(DiffuseDir.xyz, r0.xyz)) * DiffuseColor.rgb;
    r1.w = IN.position.w;
    r1.xy = (((sin(fracr((q0.x / 128) + WindData.w)) * WindData.z) * sqr(IN.color_0.a)) * WindData.xy) + r1.xy;
    r1.xyz = r1.xyz + InstanceData[0 + IN.texcoord_1.x].xyz;
    r0 = mul(ModelViewProj, r1);
	r1.xy = saturate((length(r0.xyzw) - AlphaParam.xz) / AlphaParam.yw);
	OUT.color_0.a = 1 - saturate((FogParam.x - length(r0.xyz)) / FogParam.y);
	OUT.position = r0;
    OUT.texcoord_4.xyz = AmbientColor.rgb;
    OUT.texcoord_5.w = r1.x * (1 - r1.y);
    OUT.texcoord_5.xyz = r2.xyz * AddlParams.x;
    OUT.texcoord_6 = mul(r0, TESR_ShadowCameraToLightTransformNear);
    OUT.texcoord_7 = mul(r0, TESR_ShadowCameraToLightTransformFar);
    OUT.texcoord_8 = r0;
	
    return OUT;
};

// approximately 103 instruction slots used
